name: lab1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_3d_choice_chip: ^0.1.4
  page_transition: ^2.0.5
  pretty_gauge: ^1.0.1
  share_plus: ^4.0.4
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
